const LOGIN_USER = 'LOGIN_USER';
const SIGNUP = 'SIGN_UP_USER';
const LOADING ='LOADING';
const LOGIN_ERROR ='LOGIN_ERROR';
const SIGNUP_ERROR='SIGNUP_ERROR';
const SIGNUP_USER='SIGNUP_USER';
const POST_QUESTION='POST_QUESTION';
const POST_QUESTION_ERROR='POST_QUESTION_ERROR';
const FETCH_QUESTIONS='FETCH_QUESTIONS';
const FETCH_QUESTIONS_ERROR='FETCH_QUESTIONS_ERROR';

export {
    LOGIN_USER,
    SIGNUP,
    LOADING,
    LOGIN_ERROR,
    SIGNUP_USER,
    SIGNUP_ERROR,
    POST_QUESTION,
    POST_QUESTION_ERROR,
    FETCH_QUESTIONS,
    FETCH_QUESTIONS_ERROR
}
