const LOGIN_USER = 'LOGIN_USER';
const SIGNUP = 'SIGN_UP_USER';
const LOADING ='LOADING';
const LOGIN_ERROR ='LOGIN_ERROR';
const SIGNUP_ERROR='SIGNUP_ERROR';
const SIGNUP_USER='SIGNUP_USER';

export {
    LOGIN_USER,
    SIGNUP,
    LOADING,
    LOGIN_ERROR,
    SIGNUP_USER,
    SIGNUP_ERROR,
}
